<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="" lang="">
<head>
  <title>Test Results Report - Selenium - TestNG - FireFox on Windows</title>
  <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
  <meta name="description" content="TestNG unit test results." />
  <link href="reportng.css" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="reportng.js"></script>
</head>
<body>
<h1>Selenium - TestNG - FireFox on Windows</h1>
<p>
  Test duration: 105.062s
</p>



  <table class="resultsTable">
    <tr><th colspan="4" class="header failed">Failed Tests</th></tr>
          <tr>
        <td colspan="4" class="group">rakuten.GI_MyAccountverification_v1</td>
      </tr>
            
<tr>

  <td class="method">
    <a href="javascript:void(0)" onclick="clickHandler(this);" title="Click to expand/collapse">
                  <span class="description" title="Open My Account">TC001_Open_My_Account</span>
         </a>
  </td>
  
  <td class="TMDes">Open My Account</td>

  <td class="duration">
    104.541s
  </td>
  <td class="result">
        
          <i>Method arguments: </i><span class="arguments">"http://www.rakuten.co.id", "test.rakuten26@gmail.com", "rakuten01"</span><br />
            


        <a href="javascript:toggleElement('exception-0', 'block')" title="Click to expand/collapse"><b>java.lang.Throwable: Mulitple failures (7):<br/>
Failure 1 of 7<br/>
java.lang.AssertionError: expected [true] but found [false]<br/>
	at org.testng.Assert.fail(Assert.java:94)<br/>
	at org.testng.Assert.failNotEquals(Assert.java:494)<br/>
	at org.testng.Assert.assertEquals(Assert.java:123)<br/>
	at org.testng.Assert.assertEquals(Assert.java:165)<br/>
	at com.logigear.selenium.QTiumAssert.verifyEquals(QTiumAssert.java:54)<br/>
	at com.logigear.selenium.QTiumAssert.verifyEquals(QTiumAssert.java:67)<br/>
	at rakuten.AccountSettingAction.CheckControlsExist(AccountSettingAction.java:20)<br/>
	at rakuten.GI_MyAccountverification_v1.TC001_Open_My_Account(GI_MyAccountverification_v1.java:49)<br/>
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br/>
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br/>
	at java.lang.reflect.Method.invoke(Unknown Source)<br/>
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)<br/>
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br/>
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br/>
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br/>
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br/>
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br/>
	at org.testng.TestRunner.privateRun(TestRunner.java:767)<br/>
	at org.testng.TestRunner.run(TestRunner.java:617)<br/>
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br/>
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)<br/>
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)<br/>
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)<br/>
	at java.util.concurrent.FutureTask.run(Unknown Source)<br/>
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)<br/>
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)<br/>
	at java.lang.Thread.run(Unknown Source)<br/>
<br/>
Failure 2 of 7<br/>
java.lang.AssertionError: expected [true] but found [false]<br/>
	at org.testng.Assert.fail(Assert.java:94)<br/>
	at org.testng.Assert.failNotEquals(Assert.java:494)<br/>
	at org.testng.Assert.assertEquals(Assert.java:123)<br/>
	at org.testng.Assert.assertEquals(Assert.java:165)<br/>
	at com.logigear.selenium.QTiumAssert.verifyEquals(QTiumAssert.java:54)<br/>
	at com.logigear.selenium.QTiumAssert.verifyEquals(QTiumAssert.java:67)<br/>
	at rakuten.AccountSettingAction.CheckControlsExist(AccountSettingAction.java:22)<br/>
	at rakuten.GI_MyAccountverification_v1.TC001_Open_My_Account(GI_MyAccountverification_v1.java:49)<br/>
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br/>
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br/>
	at java.lang.reflect.Method.invoke(Unknown Source)<br/>
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)<br/>
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br/>
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br/>
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br/>
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br/>
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br/>
	at org.testng.TestRunner.privateRun(TestRunner.java:767)<br/>
	at org.testng.TestRunner.run(TestRunner.java:617)<br/>
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br/>
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)<br/>
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)<br/>
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)<br/>
	at java.util.concurrent.FutureTask.run(Unknown Source)<br/>
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)<br/>
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)<br/>
	at java.lang.Thread.run(Unknown Source)<br/>
<br/>
Failure 3 of 7<br/>
java.lang.AssertionError: expected [true] but found [false]<br/>
	at org.testng.Assert.fail(Assert.java:94)<br/>
	at org.testng.Assert.failNotEquals(Assert.java:494)<br/>
	at org.testng.Assert.assertEquals(Assert.java:123)<br/>
	at org.testng.Assert.assertEquals(Assert.java:165)<br/>
	at com.logigear.selenium.QTiumAssert.verifyEquals(QTiumAssert.java:54)<br/>
	at com.logigear.selenium.QTiumAssert.verifyEquals(QTiumAssert.java:67)<br/>
	at rakuten.AccountSettingAction.CheckControlsExist(AccountSettingAction.java:24)<br/>
	at rakuten.GI_MyAccountverification_v1.TC001_Open_My_Account(GI_MyAccountverification_v1.java:49)<br/>
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br/>
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br/>
	at java.lang.reflect.Method.invoke(Unknown Source)<br/>
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)<br/>
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br/>
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br/>
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br/>
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br/>
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br/>
	at org.testng.TestRunner.privateRun(TestRunner.java:767)<br/>
	at org.testng.TestRunner.run(TestRunner.java:617)<br/>
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br/>
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)<br/>
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)<br/>
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)<br/>
	at java.util.concurrent.FutureTask.run(Unknown Source)<br/>
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)<br/>
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)<br/>
	at java.lang.Thread.run(Unknown Source)<br/>
<br/>
Failure 4 of 7<br/>
java.lang.AssertionError: expected [true] but found [false]<br/>
	at org.testng.Assert.fail(Assert.java:94)<br/>
	at org.testng.Assert.failNotEquals(Assert.java:494)<br/>
	at org.testng.Assert.assertEquals(Assert.java:123)<br/>
	at org.testng.Assert.assertEquals(Assert.java:165)<br/>
	at com.logigear.selenium.QTiumAssert.verifyEquals(QTiumAssert.java:54)<br/>
	at com.logigear.selenium.QTiumAssert.verifyEquals(QTiumAssert.java:67)<br/>
	at rakuten.AccountSettingAction.CheckControlsExist(AccountSettingAction.java:26)<br/>
	at rakuten.GI_MyAccountverification_v1.TC001_Open_My_Account(GI_MyAccountverification_v1.java:49)<br/>
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br/>
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br/>
	at java.lang.reflect.Method.invoke(Unknown Source)<br/>
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)<br/>
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br/>
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br/>
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br/>
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br/>
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br/>
	at org.testng.TestRunner.privateRun(TestRunner.java:767)<br/>
	at org.testng.TestRunner.run(TestRunner.java:617)<br/>
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br/>
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)<br/>
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)<br/>
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)<br/>
	at java.util.concurrent.FutureTask.run(Unknown Source)<br/>
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)<br/>
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)<br/>
	at java.lang.Thread.run(Unknown Source)<br/>
<br/>
Failure 5 of 7<br/>
java.lang.AssertionError: expected [true] but found [false]<br/>
	at org.testng.Assert.fail(Assert.java:94)<br/>
	at org.testng.Assert.failNotEquals(Assert.java:494)<br/>
	at org.testng.Assert.assertEquals(Assert.java:123)<br/>
	at org.testng.Assert.assertEquals(Assert.java:165)<br/>
	at com.logigear.selenium.QTiumAssert.verifyEquals(QTiumAssert.java:54)<br/>
	at com.logigear.selenium.QTiumAssert.verifyEquals(QTiumAssert.java:67)<br/>
	at rakuten.AccountSettingAction.CheckControlsExist(AccountSettingAction.java:28)<br/>
	at rakuten.GI_MyAccountverification_v1.TC001_Open_My_Account(GI_MyAccountverification_v1.java:49)<br/>
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br/>
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br/>
	at java.lang.reflect.Method.invoke(Unknown Source)<br/>
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)<br/>
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br/>
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br/>
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br/>
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br/>
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br/>
	at org.testng.TestRunner.privateRun(TestRunner.java:767)<br/>
	at org.testng.TestRunner.run(TestRunner.java:617)<br/>
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br/>
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)<br/>
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)<br/>
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)<br/>
	at java.util.concurrent.FutureTask.run(Unknown Source)<br/>
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)<br/>
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)<br/>
	at java.lang.Thread.run(Unknown Source)<br/>
<br/>
Failure 6 of 7<br/>
java.lang.AssertionError: expected [true] but found [false]<br/>
	at org.testng.Assert.fail(Assert.java:94)<br/>
	at org.testng.Assert.failNotEquals(Assert.java:494)<br/>
	at org.testng.Assert.assertEquals(Assert.java:123)<br/>
	at org.testng.Assert.assertEquals(Assert.java:165)<br/>
	at com.logigear.selenium.QTiumAssert.verifyEquals(QTiumAssert.java:54)<br/>
	at com.logigear.selenium.QTiumAssert.verifyEquals(QTiumAssert.java:67)<br/>
	at rakuten.AccountSettingAction.CheckControlsExist(AccountSettingAction.java:36)<br/>
	at rakuten.GI_MyAccountverification_v1.TC001_Open_My_Account(GI_MyAccountverification_v1.java:49)<br/>
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br/>
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br/>
	at java.lang.reflect.Method.invoke(Unknown Source)<br/>
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)<br/>
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br/>
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br/>
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br/>
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br/>
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br/>
	at org.testng.TestRunner.privateRun(TestRunner.java:767)<br/>
	at org.testng.TestRunner.run(TestRunner.java:617)<br/>
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br/>
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)<br/>
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)<br/>
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)<br/>
	at java.util.concurrent.FutureTask.run(Unknown Source)<br/>
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)<br/>
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)<br/>
	at java.lang.Thread.run(Unknown Source)<br/>
<br/>
Failure 7 of 7<br/>
java.lang.AssertionError: expected [true] but found [false]</b></a><br />
    <div class="stackTrace" id="exception-0">
              org.testng.Assert.fail(Assert.java:94)<br />
              org.testng.Assert.failNotEquals(Assert.java:494)<br />
              org.testng.Assert.assertEquals(Assert.java:123)<br />
              org.testng.Assert.assertEquals(Assert.java:165)<br />
              com.logigear.selenium.QTiumAssert.verifyEquals(QTiumAssert.java:54)<br />
              com.logigear.selenium.QTiumAssert.verifyEquals(QTiumAssert.java:67)<br />
              rakuten.AccountSettingAction.CheckControlsExist(AccountSettingAction.java:38)<br />
              rakuten.GI_MyAccountverification_v1.TC001_Open_My_Account(GI_MyAccountverification_v1.java:49)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br />
              org.testng.SuiteRunner.access$000(SuiteRunner.java:37)<br />
              org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)<br />
              org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)<br />
              java.util.concurrent.FutureTask.run(Unknown Source)<br />
              java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)<br />
              java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)<br />
              java.lang.Thread.run(Unknown Source)<br />
                </div>
      </td>
</tr>
      </table>


  
</body>
</html>
